// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: favorite_movies.sql

package db

import (
	"context"
)

const addMovie = `-- name: AddMovie :one
INSERT INTO favorite_movies(tmdb_id, title) VALUES ($1, $2) RETURNING movie_id, tmdb_id, title
`

type AddMovieParams struct {
	TmdbID string
	Title  string
}

func (q *Queries) AddMovie(ctx context.Context, arg AddMovieParams) (FavoriteMovie, error) {
	row := q.db.QueryRowContext(ctx, addMovie, arg.TmdbID, arg.Title)
	var i FavoriteMovie
	err := row.Scan(&i.MovieID, &i.TmdbID, &i.Title)
	return i, err
}

const listMovies = `-- name: ListMovies :many
SELECT movie_id, tmdb_id, title FROM favorite_movies
`

func (q *Queries) ListMovies(ctx context.Context) ([]FavoriteMovie, error) {
	rows, err := q.db.QueryContext(ctx, listMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FavoriteMovie
	for rows.Next() {
		var i FavoriteMovie
		if err := rows.Scan(&i.MovieID, &i.TmdbID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
