// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	AddMovie(ctx context.Context, arg AddMovieParams) (FavoriteMovie, error)
	ListMovies(ctx context.Context) ([]FavoriteMovie, error)
}

var _ Querier = (*Queries)(nil)
