name: build
on: 
  push:
    branches:
    - master
    - new-kelly-trial

jobs: 
  build: 
    name: Run web app
    runs-on: ubuntu-latest
    steps: 
      - name: Build web app 
        uses: actions/checkout@v2

      
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with: 
          owner: hashicorp
          repo: immutable-infrastructure
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          github_user: sabinlehaci
          workflow_file_name: github-actions.yml
          trigger_workflow: true
          ref: update-tfc-backend

      - name: Deploy Web App 
        run: | 
          echo "Deploy Web App"
          sleep 10s 



