name: build 
on: 
  push:
    branches:
    - master
    - new-kelly-trial
  workflow_dispatch: 
    inputs: 
      workflow2_name: 
        description: Deploy triggering
        required: true
        default: 'Deploy'

      workflow2_github_account:
        description: 'Github Account Owner'
        required: true 
        default: 'hashicorp'
      
      workflow2_repo_github: 
        description: 'GitHub Repository Name'
        required: true 
        default: 'immutable-infrastructure'

              
jobs: 
  build: 
    name: Run web app
    runs-on: ubuntu-latest
      
    steps: 
      
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Deploy Web App 
        run: | 
          cd "$GITHUB_WORKSPACE/Deployment-Scripts/"
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dotenv
          echo "Deploy Web App"
          sleep 10s

      - name: Deploy Web App 
        run: | 
          cd "$GITHUB_WORKSPACE/Deployment-Scripts/"
          python $GITHUB_WORKSPACE/Deployment-Scripts/workflow_trigger.py
    
    


        




